### ISSUE TITLE
Consider adding the TOC to the run html outputs

### ISSUE THREAD

**Issue by Polkas** [NovoNordisk-OpenSource/whirl#107]
Adding a table of content at the top of docs can significantly help end users

**Comment by Lovemore-Gakava** [comment]
@Polkas thanks for the comment - just checking: for each html log there is a floating ToC see: https://novonordisk-opensource.github.io/whirl/articles/example_log.html. Are you referring to a different document?

**Comment by Polkas** [comment]
I confimed it now, toc is there but for desktops. When I open the file with my IPhone it is not there:)

**Comment by Lovemore-Gakava** [comment]
@Polkas thanks for confirming -  we will keep in mind that the output needs to be compatible with other devices as well!

**Comment by akselthomsen** [comment]
@Polkas and @Lovemore-Gakava, I took another look at it, and it looks to be a general request for Quarto that the ToC is also shown in narrow displays (https://github.com/quarto-dev/quarto-cli/issues/5961).

As a side note it does display for me when I turn my iPhone and look at the log in landscape.

**Comment by akselthomsen** [comment]
closing this issue since it seems to be more of a quarto problem than for our logs.
