### ISSUE TITLE
Important - Rethink usage of whirl with containers

### ISSUE THREAD

**Issue by Polkas** [NovoNordisk-OpenSource/whirl#108]
It seems worth to consider how to link containers in the process. For example Dockerfile can contains Linux system dependencies a and file itself has big value.

**Comment by akselthomsen** [comment]
Currently our thought would be that the user sets up an environment variable in the container identifying it, and then we will capture that value in the log.

We are also considering if we can come up with a better way to display the container information (#30)

**Comment by akselthomsen** [comment]
Extra feature will be done when completing #30
