### ISSUE TITLE
fix: Use "." instead of getwd()

### ISSUE THREAD

**Issue by Lovemore-Gakava** [NovoNordisk-OpenSource/whirl#57]
Feedback from PR #55 :  using "." is generally considered good practice because it makes the code more portable and easier to understand. When you use getwd(), it returns the absolute path of the current working directory, which can vary depending on the system or user running the script. This does not impact whirl code as the processing occurs in the temporary directory but would be great to align with good practice.

**Comment by akselthomsen** [comment]
Checked `main` branch and all uses of `getwd()` left are cases where we do need the absolute branch.
