### ISSUE TITLE
feat: Give you the option of running R scripts in the folder in which they are stored.

### ISSUE THREAD

**Issue by Cervangirard** [NovoNordisk-OpenSource/whirl#62]
The aim would be to give you the opportunity to launch the R script in the folder where it is located, as would be the case for a Rmarkdown, for example.

That could be possible if we change the behaviour of this `quarto_execute_dir`
![image](https://github.com/user-attachments/assets/5d615f34-e95f-4884-b518-688225bd4bfb)

**Comment by akselthomsen** [comment]
In #124 I have implemented a new option `execute_dir` where you can either specify a character path to be used for all scripts, or a function, that given the path to the script returns the appropriate execute dir.
