### ISSUE TITLE
bug: Using vscode produce errors

### ISSUE THREAD

**Issue by Cervangirard** [NovoNordisk-OpenSource/whirl#63]
When I m using my local vscode, I receive the error below 

quarto_render : `quarto.exe` not found

even if quarto is installed and quarto is enable to render a single qmd file

**Comment by akselthomsen** [comment]
I just tried myself, and it worked fine after I installed pandoc (instead of relying on the Studio bundled one).
@Cervangirard are we okay to close this issue?
