### ISSUE TITLE
fix: Too much deps for cran

### ISSUE THREAD

**Issue by YBqRbhWrpFAa519uZ1Vnbe3e7dOF1BdmBGtFPnu** [NovoNordisk-OpenSource/whirl#65]
![image](https://github.com/user-attachments/assets/7ed2c49d-186f-4c57-8906-7eb921078c5f)

We have to remove some of them :)

**Comment by Polkas** [comment]
+1

**Comment by Polkas** [comment]
It is a biggest blocker in the broader adoption in my personal opinion. Many packages can be replaced with base R like purrr stringr tibble or sessioninfo.
